.ONESHELL:
PHONY: install-requirements check-requirements test check clean bumpversion setup-env install-pre-commit-hook bootstrap help
NAME ?= pre-commit-config-shellcheck
EXTENSIONS ?= py,html,txt,xml,eml
TRASH_DIRS ?= build .mypy_cache .pytest_cache __pycache__ htmlcov
TRASH_FILES ?= .coverage coverage.xml *.pid Pipfile.lock
ENVIRONMENT ?= dev


install-requirements:
	python -m pip install .[$(ENVIRONMENT)];\


check-requirements:
	pip-outdated setup.cfg;\


test:
	PYTHONPATH="$${PYTHONPATH}:$${PWD}" DJANGO_SETTINGS_MODULE=$(SETTINGS) pytest --import-mode=importlib --cov=$(NAME) $(TESTS);\


check:
	pre-commit run --all-files;\


clean:
	for file in $(TRASH_FILES); do\
		find -iname $${file} -print0 | xargs -0 rm -rf;\
	done;\
	for dir in $(TRASH_DIRS); do\
		find -type d -name $${dir} ! -path "*/.direnv/*" -print0 | xargs -0 rm -rf;\
	done;\


bumpversion:
	git tag -a $(VERSION) -m "v$(VERSION)";\


setup-env:
	cp .env.example .env;\
	direnv allow;\


install-pre-commit-hook:
	pre-commit install;\


bootstrap: setup-env install-requirements install-pre-commit-hook


help:
	@echo "    help:"
	@echo "        Show this help."
	@echo "    [LOCAL DEVELOPMENT]:"
	@echo "        install-requirements:"
	@echo "            Install python requirements."
	@echo "        check-requirements:"
	@echo "            Check python outdated requirements."
	@echo "        test:"
	@echo "            Run tests, can specify tests with 'TESTS' variable."
	@echo "        check:"
	@echo "            Perform some code checks."
	@echo "        clean:"
	@echo "            Recursively delete useless autogenerated files and directories, directories and files lists can be overridden through 'TRASH_DIRS' and 'TRASH_FILES' variables."
	@echo "        bumpversion:"
	@echo "            Tag current code revision from version file."
	@echo "        setup-env:"
	@echo "            Copy example environment config for development."
	@echo "        install-pre-commit-hook:"
	@echo "            Setup pre commit hook."
	@echo "        bootstrap:"
	@echo "            Bootstrap project."
