.ONESHELL:
PHONY: install test check clean bumpversion help
NAME ?= pre-commit-config-shellcheck
TRASH_DIRS ?= build .mypy_cache .pytest_cache __pycache__ htmlcov
TRASH_FILES ?= .coverage coverage.xml *.pid Pipfile.lock
ENVIRONMENT ?= dev


install:
	python -m pip install .[$(ENVIRONMENT)];\


test:
	pytest -v tests --cov=pre_commit_config_shellcheck $(TESTS);\


check:
	pre-commit run --all-files;\


clean:
	for file in $(TRASH_FILES); do\
		find -iname $${file} -print0 | xargs -0 rm -rf;\
	done;\
	for dir in $(TRASH_DIRS); do\
		find -type d -name $${dir} ! -path "*/.direnv/*" -print0 | xargs -0 rm -rf;\
	done;\


bumpversion:
	git tag -a $(VERSION) -m "v$(VERSION)";\


help:
	@echo "    help:"
	@echo "        Show this help."
	@echo "    [LOCAL DEVELOPMENT]:"
	@echo "        install:"
	@echo "            Install python requirements."
	@echo "        test:"
	@echo "            Run tests, can specify tests with 'TESTS' variable."
	@echo "        check:"
	@echo "            Perform some code checks."
	@echo "        clean:"
	@echo "            Recursively delete useless autogenerated files and directories, directories and files lists can be overridden through 'TRASH_DIRS' and 'TRASH_FILES' variables."
	@echo "        bumpversion:"
	@echo "            Tag current code revision from version file."
